export const SET_BASKET = 'SET_BASKET';
export const SET_BASKET_ITEM = 'SET_BASKET_ITEM';
export const CHANGE_BASKET_ITEM_COUNT = 'CHANGE_BASKET_ITEM_COUNT';
export const CLEAR_BASKET = 'CLEAR_BASKET';
